# Copyright (C) 2019 Intel Corp.
# 
# SPDX-License-Identifier: Apache-2.0

[Writable]
LogLevel = "DEBUG"

[Service]
Host = "device-scale"
Port = 26599
ConnectRetries = 3
Labels = []
OpenMsg = "device scale started"
ReadMaxLimit = 256
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "edgex-core-consul"
Port = 8500
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10
Type = "consul"

[Logging]
EnableRemote = true
File = "/edgex/logs/device-random.log"

[Clients]
  [Clients.Data]
  Protocol = "http"
  Host = "edgex-core-data"
  Port = 48080
  Timeout = 5000

  [Clients.Metadata]
  Protocol = "http"
  Host = "edgex-core-metadata"
  Port = 48081
  Timeout = 5000

  [Clients.Logging]
  Protocol = "http"
  Host = "edgex-support-logging"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./res"

[Driver]
  DeviceName = "device-scale"
  SimulatorPort = "8081"
  ScaleID = "123"
  LaneID = "123"
  ScaleVID = "0403"
  ScalePID = "6001" 
  TimeOutMilli = "500"
 
# Pre-define Devices
[[DeviceList]]
  Name = "device-scale"
  Profile = "device-scale-profile"
  Description = "device-scale-description"
  Labels = [ "device-scale-label" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
      Address = "device-scale-01"
      Port = "300"
  [[DeviceList.AutoEvents]]
    Frequency = "1s"
    OnChange = true
    Resource = "weight"
