rrpBuildGoCode {
    projectKey = 'loss-detector'
    buildImage = 'amr-registry.caas.intel.com/rrp/ci-go-build-image:git-1.12.0-alpine'
    ecrRegistry = "280211473891.dkr.ecr.us-west-2.amazonaws.com"
    dependencyManager = 'gomod'
    buildPackages      = 'apk add --update --no-cache make git gcc libc-dev libsodium-dev zeromq-dev'
    buildCommand       = "CGO_ENABLED=1 go build -a -installsuffix cgo -o ${projectKey} ./main.go"
    testStepsInParallel = false
    dockerImageName = "loss-detection/${projectKey}"
    dockerBuildOptions = ['--squash', '--build-arg GIT_COMMIT=$GIT_COMMIT']
    pushImage = false // dont push harbor images 
    protexProjectName = "LossDetection-loss-detector"
}