rrpBuildGoCode {
    projectKey = 'event-reconciler'
    buildImage = 'amr-registry.caas.intel.com/rrp/ci-go-build-image:1.11-alpine'
    ecrRegistry = "280211473891.dkr.ecr.us-west-2.amazonaws.com"
    dependencyManager = 'gomod'
    buildPackages      = 'apk add --update --no-cache make git gcc libc-dev libsodium-dev zeromq-dev'
    buildCommand       = "GO111MODULE=on CGO_ENABLED=1 go build -a -installsuffix cgo -o ${projectKey} ./main.go"
    testStepsInParallel = false
    dockerImageName = "loss-detection/${projectKey}"
    dockerBuildOptions = ['--squash', '--build-arg GIT_COMMIT=$GIT_COMMIT']
    pushImage = false
    protexProjectName = "LossDetection-event-reconciler"
}
