# Copyright (C) 2019 - 2022 Intel Corp.
# 
# SPDX-License-Identifier: Apache-2.0

[Writable]
LogLevel = 'INFO'

[Service]
HealthCheckInterval = '10s'
Host = 'localhost'
MaxRequestSize = 0
MaxResultCount = 0
Port = 48096
ReadMaxLimit = 100
RequestTimeout = '30s'
ServerBindAddr = ""
StartupMsg = 'RSP Event Handler App has started'

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Clients]
  [Clients.core-metadata]
  Protocol = "http"
  Host = "localhost"
  Port = 59881

[Trigger]
Type="edgex-messagebus"
  [Trigger.EdgexMessageBus]
  Type = "mqtt"
    [Trigger.EdgexMessageBus.SubscribeHost]
    Host = "localhost"
    Port = 1883
    Protocol = "tcp"
    SubscribeTopics="edgex/events/#"
    [Trigger.EdgexMessageBus.PublishHost]
    Host = "localhost"
    Port = 1883
    Protocol = "tcp"
    PublishTopic="edgex/events/device/{profilename}/{devicename}/{sourcename}" 
    [Trigger.EdgexMessageBus.Optional]
    authmode = "none"
    ClientId ="rsp-event-handler"
    Qos =  "0" # Quality of Sevice values are 0 (At most once), 1 (At least once) or 2 (Exactly once)
    KeepAlive =  "10" # Seconds (must be 2 or greater)
    Retained = "false"
    AutoReconnect = "true"
    ConnectTimeout = "5" # Seconds
    SkipCertVerify = "false"

[ApplicationSettings]
DeviceNames = "rsp-controller"
ValueDescriptorToFilter = "inventory_event"
