# Copyright (C) 2022 Intel Corp.
# 
# SPDX-License-Identifier: Apache-2.0

# Pre-define Devices
[[DeviceList]]
  Name = "device-pos-rest"
  ProfileName = "device-pos-rest"
  Description = "RESTful Device that sends in JSON POS data"
  Labels = [ "REST", "json", "pos" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
[[DeviceList]]
  Name = "device-cv-roi-rest"
  ProfileName = "device-cv-roi-rest"
  Description = "RESTful device for CV ROI events"
  Labels = [ "REST", "cv", "ROI"]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
[[DeviceList]]
  Name = "device-rfid-roi-rest"
  ProfileName = "device-rfid-roi-rest"
  Description = "RESTful device for RFID ROI events"
  Labels = [ "REST", "RFID", "ROI"]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
[[DeviceList]]
  Name = "device-scale-rest"
  ProfileName = "device-scale-rest"
  Description = "RESTful device for Scale"
  Labels = [ "REST", "scale"]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]