[Writable]
LogLevel = "INFO"
# InsecureSecrets are required for when Redis is used for message bus
  [Writable.InsecureSecrets]
    [Writable.InsecureSecrets.DB]
    path = "redisdb"
      [Writable.InsecureSecrets.DB.Secrets]
      username = ""
      password = ""
  [Writable.Reading]
  ReadingUnits = true

[Service]
Host = "localhost"
Port = 49986
HealthCheckInterval = '10s'
StartupMsg = "Device REST started"
RequestTimeout = "5s"
MaxRequestSize = 0
ServerBindAddr = ""  # if blank, uses default Go behavior https://golang.org/pkg/net/#Listen
MaxResultCount = 0

[Registry]
Host = "localhost"
Port = 8500
Type = "consul"
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10

[Clients]
  [Clients.Data]
  Protocol = "http"
  Host = "localhost"
  Port = 48080

  [Clients.Metadata]
  Protocol = "http"
  Host = "localhost"
  Port = 48081

[Device]
  DataTransform = true
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  ProfilesDir = "./res/profiles"
  DevicesDir = "./res/devices"
  Labels = []
  EnableAsyncReadings = true
  AsyncBufferSize = 16
  UseMessageBus = true
    [Device.Discovery]
    Enabled = false
    Interval = "30s"

[MessageQueue]
Protocol = "tcp"
Host = "localhost"
Port = 1883
Type = "mqtt"
AuthMode = "none"
PublishTopicPrefix = "edgex/events/device" # /<device-profile-name>/<device-name>/<source-name> will be added to this Publish Topic prefix
  [MessageQueue.Optional]
  ClientId = "device-checkout-rest"
  Qos = "0" # Quality of Sevice values are 0 (At most once), 1 (At least once) or 2 (Exactly once)
  KeepAlive = "10" # Seconds (must be 2 or greater)
  Retained = "false"
  AutoReconnect = "true"
  ConnectTimeout = "5" # Seconds
  SkipCertVerify = "false" # Only used if Cert/Key file or Cert/Key PEMblock are specified

# Driver configs
[Driver]
Port = "48085"
Timeout = "5000"